### ISSUE TITLE
Sum changes internal state

### ISSUE THREAD

**Issue by kr** [codahale/blake2#2]
It looks like digest.Sum modifies its internal state:

https://github.com/codahale/blake2/blob/3fa823583a/blake2b.go#L153

```go
C.blake2b_final(d.state, (*C.uint8_t)(&digest[0]), C.uint8_t(d.Size()))
```

The contract for hash.Hash.Sum prohibits this:

https://godoc.org/hash#Hash.Sum
> Sum appends the current hash to b and returns the resulting slice.
> It does not change the underlying hash state.

The user should be able to get the sum, then continue writing, then get another sum, etc. Other crypto hash implementations with this problem (where computing the sum is destructive) conform to this requirement by copying the internal state before summing. For example, 

https://github.com/golang/go/blob/53c92f95a8/src/crypto/sha256/sha256.go#L129-L130

and

https://github.com/golang/crypto/blob/aedad9a179/sha3/sha3.go#L187-L189

The allocation is unfortunate, but necessary.

I'm pretty sure this could be fixed the same way in this package. Looks like blake2b_state has no internal pointers so it should be safe to copy. Maybe like:

```go
unc (d *digest) Sum(buf []byte) []byte {
	digest := make([]byte, d.Size())
	// Make a copy of d.state so that caller can keep writing and summing.
	s := *d.state
	C.blake2b_final(&s, (*C.uint8_t)(&digest[0]), C.uint8_t(d.Size()))
	return append(buf, digest...)
}
```

**Comment by codahale** [comment]
I would accept a PR to fix this.

**Comment by kr** [comment]
Cool. Coming up.
